# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_forward(object):
    def setupUi(self, forward):
        forward.setObjectName("forward")
        forward.resize(690, 375)
        font = QtGui.QFont()
        font.setPointSize(12)
        forward.setFont(font)
        self.forward_2 = QtWidgets.QPushButton(forward)
        self.forward_2.setGeometry(QtCore.QRect(90, 190, 93, 61))
        self.forward_2.setObjectName("forward_2")
        self.left = QtWidgets.QPushButton(forward)
        self.left.setGeometry(QtCore.QRect(0, 250, 93, 51))
        self.left.setObjectName("left")
        self.right = QtWidgets.QPushButton(forward)
        self.right.setGeometry(QtCore.QRect(180, 250, 93, 51))
        self.right.setObjectName("right")
        self.backward = QtWidgets.QPushButton(forward)
        self.backward.setGeometry(QtCore.QRect(90, 300, 93, 61))
        self.backward.setObjectName("backward")
        self.horizontalSlider = QtWidgets.QSlider(forward)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 80, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.up = QtWidgets.QPushButton(forward)
        self.up.setGeometry(QtCore.QRect(460, 190, 93, 51))
        self.up.setObjectName("up")
        self.down = QtWidgets.QPushButton(forward)
        self.down.setGeometry(QtCore.QRect(460, 250, 93, 51))
        self.down.setObjectName("down")
        self.lcdNumber = QtWidgets.QLCDNumber(forward)
        self.lcdNumber.setGeometry(QtCore.QRect(510, 80, 111, 51))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(forward)
        self.label.setGeometry(QtCore.QRect(20, 20, 141, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(forward)
        self.label_2.setGeometry(QtCore.QRect(520, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(forward)
        self.label_3.setGeometry(QtCore.QRect(44, 115, 91, 31))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(forward)
        self.horizontalSlider.valueChanged['int'].connect(self.label_3.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(forward)

    def retranslateUi(self, forward):
        _translate = QtCore.QCoreApplication.translate
        forward.setWindowTitle(_translate("forward", "Dialog"))
        self.forward_2.setText(_translate("forward", "forward"))
        self.left.setText(_translate("forward", "left"))
        self.right.setText(_translate("forward", "right"))
        self.backward.setText(_translate("forward", "backward"))
        self.up.setText(_translate("forward", "up"))
        self.down.setText(_translate("forward", "down"))
        self.label.setText(_translate("forward", "control speed"))
        self.label_2.setText(_translate("forward", "sensor"))


